name: Quarentena_Tech
description: Aplicação para a quarentena tech, que é um projeto liderado pelo o Marco Bruno da CollabCode com o intuito de divulgar conteúdos relacionado ao mundo da tecnologia.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  share: ^0.6.3+6
  flutter_svg: ^0.17.4
  url_launcher: ^5.4.2
  transparent_image: ^1.0.0
  shared_preferences: ^0.5.6+3
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: fonts/PressStart2P-Regular.ttf
  assets:
    - images/